name: build and release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'

      - name: Build
        run: |
          go build -o ddman

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: ddman-binary
          path: ddman
  
  release:
    name: project release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v0.0.1 --title "ddman, the download manager" --target main ddman